import NavBar from "@/components/frontend/navbar/NavBar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import "swiper/css";
import { AuthProvider } from "@/providers/Providers";
import Footer from "@/components/frontend/footer/Footer";
import { Toaster } from "@/components/ui/toaster";
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Point Batteries Service",
  description: "Generated by create next app",
};
export default function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased `}>
        <AuthProvider>
          <NavBar />
          <Toaster />
          <div className="min-h-[650px] bg-gray-50">{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
